### ISSUE TITLE
[Deepak Foundation] Visit scheduling 

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/Deepak-Foundation#5]
- [x] Baseline screening form should be scheduled as soon as enrollment in program is done.
- [x] Midline screening should be scheduled three month after completion of the Baseline screening.
- [x] Endline screening should be scheduled three month after the completion of Midline screening.
- [x] After Baseline screening, if HB recorded is less than or equal to 7.9, then schedule severe Anemia follow-up after a month. The follow-up will continue till Endline screening if the HB stays below 7.9 or equal. 
- [x] If "Does she remain absent during menstruation" answer is Yes, then schedule Menstrual absenteeism follow-up after a month.
- [x] If in Menstrual absenteeism, "do you still remain absent due to menstrual problem?" answer is No, then stop scheduling menstrual absenteeism follow-up.
- [x] In Midline screening, if Blood sample collected answer is Yes, schedule Record blood sample result form after a week.

**Comment by Gojo-Taqi** [comment]
Stop scheduling severe anemia follow-up if HB is recorded more than 7.9 in Midline screening.
Will talk to BA about this point.

**Comment by Gojo-Taqi** [comment]
- [x] If the individual has anwer "Dropped out" for the question "Going to school", then none of the visits should be scheduled.

**Comment by Dinesh2019** [comment]
- [x]  All visits should stop being scheduled once the endline screening is completed 
![image.png](https://images.zenhubusercontent.com/640ef9e3ad2fcf337b550a3f/878ea956-8122-416b-ad45-aed0b7e6a0af)

**Comment by Gojo-Taqi** [comment]
Fixed the issues, right now if endline is completed, then severe anemia and menstrual absenteeism will not be scheduled.

**Comment by Dinesh2019** [comment]
- [x] If we do the visit for severe anemia follow-up is done before the end-line screening it is scheduling the follow-up after completing end-line screening still see the scheduled follow up but excepted I should be removed after the end-line screening is done
Discussed with Utkarsh we can  see that if the scheduled date is coming after endline then not scheduling it. 

- [x] If we edit the visit for completing the visit get scheduled again
![image.png](https://images.zenhubusercontent.com/640ef9e3ad2fcf337b550a3f/b11e553a-ffb6-4224-8a2f-9a93bf354cd1)
After edit again the blood sample is scheduled 
![image.png](https://images.zenhubusercontent.com/640ef9e3ad2fcf337b550a3f/c30a25b9-e9be-413d-859f-e9fc981bc00b)
